export const assets = [
  {
    id: "1",
    title: "Distribution Report Q1",
    description:
      "An in-depth look at distribution channels performance in Q1.",
    tags: ["#distribution", "#logistics", "#q1"],
    used: 342,
    type: "Report",
    pages: 24,
    lastUpdated: "2025-03-01T10:15:00Z",
    kpiData: [
      { name: "Reach", value: 75 },
      { name: "Coverage", value: 60 },
      { name: "Fulfillment", value: 85 },
    ],
  },
  {
    id: "2",
    title: "E‑commerce Trends 2024",
    description: "Key trends and insights shaping online retail in 2024.",
    tags: ["#ecomm", "#retail", "#trends"],
    used: 587,
    type: "Report",
    pages: 30,
    lastUpdated: "2025-02-20T14:30:00Z",
    kpiData: [
      { name: "Conversion Rate", value: 5 },
      { name: "AOV", value: 120 },
      { name: "Cart Abandonment", value: 40 },
    ],
  },
  {
    id: "3",
    title: "Social Media Marketing Guide",
    description:
      "Best practices for engaging audiences across social platforms.",
    tags: ["#marketing", "#social", "#guide"],
    used: 421,
    type: "Guide",
    pages: 18,
    lastUpdated: "2025-01-15T08:00:00Z",
    kpiData: [
      { name: "Engagement", value: 65 },
      { name: "Impressions", value: 90 },
      { name: "Shares", value: 50 },
    ],
  },
  {
    id: "4",
    title: "SEO Performance Overview",
    description: "Analysis of organic search performance over the last year.",
    tags: ["#seo", "#marketing", "#performance"],
    used: 304,
    type: "Dashboard",
    pages: 12,
    lastUpdated: "2025-03-10T16:45:00Z",
    kpiData: [
      { name: "Organic Traffic", value: 1500 },
      { name: "Keyword Rank", value: 10 },
      { name: "Backlinks", value: 200 },
    ],
  },
  {
    id: "5",
    title: "Affiliate Marketing Stats",
    description: "Detailed statistics from our affiliate programs.",
    tags: ["#affiliate", "#ecomm", "#stats"],
    used: 289,
    type: "Report",
    pages: 22,
    lastUpdated: "2025-02-05T12:00:00Z",
    kpiData: [
      { name: "Clicks", value: 1200 },
      { name: "Conversions", value: 180 },
      { name: "Revenue", value: 9500 },
    ],
  },
  {
    id: "6",
    title: "Content Distribution Plan",
    description: "Strategy for distributing content across owned channels.",
    tags: ["#content", "#distribution", "#strategy"],
    used: 176,
    type: "Plan",
    pages: 15,
    lastUpdated: "2025-01-25T09:20:00Z",
    kpiData: [
      { name: "Publish Frequency", value: 10 },
      { name: "Reach", value: 80 },
      { name: "Engagement", value: 55 },
    ],
  },
  {
    id: "7",
    title: "Email Campaign Analysis",
    description: "Performance metrics from recent email marketing campaigns.",
    tags: ["#email", "#marketing", "#campaign"],
    used: 412,
    type: "Report",
    pages: 16,
    lastUpdated: "2025-02-28T11:10:00Z",
    kpiData: [
      { name: "Open Rate", value: 22 },
      { name: "Click‑Through Rate", value: 8 },
      { name: "Bounce Rate", value: 3 },
    ],
  },
  {
    id: "8",
    title: "Digital Ad Spend Report",
    description: "Overview of ad spend and ROI across channels.",
    tags: ["#ads", "#spend", "#roi"],
    used: 653,
    type: "Report",
    pages: 28,
    lastUpdated: "2025-03-12T13:50:00Z",
    kpiData: [
      { name: "Spend", value: 45000 },
      { name: "ROI", value: 2.5 },
      { name: "Impressions", value: 200000 },
    ],
  },
  {
    id: "9",
    title: "Website Traffic Dashboard",
    description: "Realtime dashboard showing site traffic metrics.",
    tags: ["#web", "#traffic", "#dashboard"],
    used: 512,
    type: "Dashboard",
    pages: 10,
    lastUpdated: "2025-03-14T07:30:00Z",
    kpiData: [
      { name: "Users", value: 3200 },
      { name: "Sessions", value: 5000 },
      { name: "Bounce Rate", value: 45 },
    ],
  },
  {
    id: "10",
    title: "Customer Acquisition Funnel",
    description: "Steps and metrics of our customer acquisition process.",
    tags: ["#acquisition", "#funnel", "#marketing"],
    used: 398,
    type: "Report",
    pages: 20,
    lastUpdated: "2025-02-18T15:00:00Z",
    kpiData: [
      { name: "Leads", value: 800 },
      { name: "MQLs", value: 200 },
      { name: "SQLs", value: 75 },
    ],
  },
];